name: Langfuse Prompt Sync

on:
  repository_dispatch:
    types: [langfuse-prompt-update]

permissions:
  contents: write
  
jobs:
  save_prompt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Save or update prompt file
        run: |
          mkdir -p prompts
          FILE="prompts/${{ github.event.client_payload.prompt.name }}.txt"
          echo "Updating prompt file: $FILE"
          echo "${{ github.event.client_payload.prompt.content }}" > "$FILE"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add prompts/
          git commit -m "Update prompt ${{ github.event.client_payload.prompt.name }} v${{ github.event.client_payload.prompt.version }}" || echo "No changes to commit"
          git push
